### ISSUE TITLE
Idee

### ISSUE THREAD

**Issue by tieskedh** [tieskedh/hack-a-drone#1]
Misschien is het een idee om net als ik de recorder en camera een superklasse te geven?

Daarnaast, misschien is liveStreamer of streamer een betere naam voor camera?

PS. code is privé. Ik wil niet dat ze als ze op"hack-a-drone" zoeken mijn code krijgen...

**Comment by nberlijn** [comment]
Je hebt het maar druk met de drone code, het is zeker een goed idee :P Misschien heb ik morgen nog wel even de tijd om de huidige code verder te optimaliseren. Echter, ik ben bang dat er morgen te weinig tijd is aangezien er ook nog andere zaken geregeld moeten worden. Mocht er morgen geen tijd zijn, dan kan er voor de volgende workshop (mits deze komt) de code sowieso geoptimaliseerd worden. Eventueel kan je hier aan meehelpen als je dat ziet zitten? Anyway, toch bedankt voor je scherpe oog!

**Comment by tieskedh** [comment]
Haha, de drone-code is leuk, maar dit is ideaal om Kotlin te bekend te maken.

Daarnaast werkt de kennis met kotlin direct terug in Java. Dat lambda-idee had ik alleen maar door Kotlin. Normaal zou ik dat idee nooit gekregen hebben...

**Comment by tieskedh** [comment]
*bekend maken is tonen aan kees

**Comment by nberlijn** [comment]
Daar heb je zeker gelijk in. Ik zie ook wel de voordelen van Kotlin in, vooral het principe dat je heel makkelijk kan switchten van Java naar Kotlin en vice versa. De uitdaging zit hem erin om het bekend te maken bij het management en grote bedrijven :P
